before:
  hooks:
    - go mod download
builds:
- 
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
